<?php

/**
 * ParameterCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParameterCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParameterCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParameterCategory');
    }
}