generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           ParameterCategory
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          parameter_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
      filter:
        display: [name, is_active]
        class:
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
      revert:  ~