generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           AdChainImage
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ad_chain_image
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        file_path: {label: "Ảnh"}
        is_active: {label: "Trạng thái"}
        priority: {label: "Sắp sếp"}
        product: {label: "Phòng"}
      list:
        display: [file_path, product, is_active, priority]
        title: Danh sánh ảnh phòng
      filter:
        display: [product, is_active]
        class: AdChainImageFormFilterAdmin
      form:
        display: [file_path, product, is_active, priority]
        class: AdChainImageFormAdmin
      edit:
        title: Thêm mới ảnh phòng
      new:
        title: Cập nhập ảnh phòng
      show:    ~
      revert:  ~