all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost:3308;dbname=dung_nehobcity'
      username: produser
      password: produser@90@!990
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
